### ISSUE TITLE
Undo/Delete Pairings

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#10]
- [x]  Change the button in OrganizerComponent to Delete Pairings
- [x]  If pairings are deleted, any user in the WebRTC room should be notified with a prompt

**Comment by Slanfan** [comment]
Updated text to **Delete active pairings**

**Comment by Slanfan** [comment]
```css
.match-deleted {
    position: relative;
    width: 50%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 10%;
    height: auto;
    padding: 2rem;
    background: var(--content-hover-title-text);
    border-radius: .25rem;
    color: var(--content-bg);
}
```
